d=int(input("Enter a decimal no"))
bs=bin(d)
os=oct(d)
hs=hex(d)
print("binary str:",bs[2:])
print("octal str:",os[2:])
print("Hex str:",hs[2:].upper())
ds1=int(bs,2)
ds2=int(os,8)
ds3=int(hs,16)
print("decimal str:",ds1)
print("decimal str:",ds2)
print("decimal str:",ds3)